set runtimepath=$SRC_DIR/2ndparty/bare-dotfiles,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim72,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,$SRC_DIR/2ndparty/bare-dotfiles/after
filetype plugin indent on
syntax enable
set nocp

